# 99 — Day 1 Spike

Pick the base VLM for the Day 2 QLoRA fine-tune by zero-shot evaluating Qwen3-VL Instruct variants and benchmarking against GPT-4o-mini on a locked 100-row test set.

## What this notebook decides

1. Which Qwen3-VL variant loads cleanly on a Colab T4 in 4-bit.
2. Whether any Qwen variant is competitive with GPT-4o-mini on parse rate, brand / category / condition / color accuracy, and price MAPE.
3. The model ID to lock for the Day 2 fine-tune.

The verdict is in the **last markdown cell**.

## What's tested

- Zero-shot inference, two German prompt variants (Vinted, Kleinanzeigen).
- Strict-JSON output parsing.
- Per-row metrics: parse rate, top-1 accuracy on categorical fields, MAPE on price.

This notebook is **zero-shot only** — no model weights are trained.

## How to run

1. Open in Colab on a free **T4** runtime (16 GB VRAM fits Qwen 2B and 4B in 4-bit; 8B is disabled by default).
2. Run cells top to bottom. Total wall-clock ~30–60 min depending on download speed.
3. Only manual step: paste `OPENAI_API_KEY` when cell 11 prompts (or set it as an env var beforehand).
4. If the data parquets are not on Drive, cell 5 raises `FileNotFoundError` pointing to the expected path: `/content/drive/MyDrive/Resell_Copilot_data/`.

## Inputs / outputs

| | |
|---|---|
| Inputs | `data/vinted_clothing_v2.parquet`, `data/kleinanzeigen_clothing_v1.parquet` |
| Locked test set | `data/splits/spike_test.parquet`, `data/splits/spike_test_ids.json` |
| Predictions | `results/spike/{model}_predictions.json` (one per model) |

All outputs are cached. Re-running any cell after its output exists is a no-op — delete the file on disk to force recompute.

## Decision rule

- **Qwen variant beats GPT-4o-mini on ≥1 of {brand, category, price MAPE}** → idea works. Lock it. Scale up Day 2.
- **Qwen variant matches GPT-4o-mini roughly across the board** → diagnose (prompt? base model? hyperparameters?) before scaling.
- **No Qwen variant is sensible** → reframe (drop price-head ambition, pitch as structured listing generation only).

In [1]:
# Pinned versions for Colab T4 stability. Re-running is a no-op once installed.
%pip install --quiet \
    "transformers>=4.51" \
    "accelerate>=1.0" \
    "bitsandbytes>=0.44" \
    "openai>=1.55" \
    "pandas>=2.2" \
    "pyarrow>=16.0" \
    "pillow>=10.3" \
    "scikit-learn>=1.5" \
    "tabulate>=0.9"


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 19.9 MB/s eta 0:00:00:00:0100:01


In [2]:
import os
import sys
import subprocess
from pathlib import Path

REPO_URL = "https://github.com/mchlkan/Advanced_ML.git"
REPO_DIR = Path("/content/Advanced_ML")

if not REPO_DIR.exists():
    subprocess.check_call(["git", "clone", REPO_URL, str(REPO_DIR)])
else:
    # Best-effort pull so the spike runs against latest data_prep.py
    subprocess.run(["git", "-C", str(REPO_DIR), "pull", "--ff-only"], check=False)

os.chdir(REPO_DIR)
SRC_DIR = str(REPO_DIR / "src")
if SRC_DIR not in sys.path:
    sys.path.insert(0, SRC_DIR)

print(f"cwd        : {os.getcwd()}")
print(f"sys.path[0]: {sys.path[0]}")


cwd        : /content/Advanced_ML
sys.path[0]: /content/Advanced_ML/src


In [3]:
import random
import numpy as np
import torch

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

print(f"PyTorch       : {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    p = torch.cuda.get_device_properties(0)
    print(f"Device        : {p.name}")
    print(f"VRAM total    : {p.total_memory / 1e9:.1f} GB")
    print(f"CUDA          : {torch.version.cuda}")


PyTorch       : 2.10.0+cu128
CUDA available: True
Device        : Tesla T4
VRAM total    : 15.6 GB
CUDA          : 12.8


In [6]:
import json
import shutil
from pathlib import Path
import pandas as pd

VINTED_FN = "vinted_clothing_v2.parquet"
KA_FN     = "kleinanzeigen_clothing_v1.parquet"
DATA_DIR    = Path("data")
SPLITS_DIR  = Path("data/splits")
RESULTS_DIR = Path("results/spike")
DATA_DIR.mkdir(parents=True, exist_ok=True)
SPLITS_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

# Bring data in from Google Drive on first run if not already local.
if not (DATA_DIR / VINTED_FN).exists() or not (DATA_DIR / KA_FN).exists():
    print("Data files not found locally — mounting Google Drive...")
    from google.colab import drive
    drive.mount("/content/drive")
    DRIVE_DATA = Path("/content/drive/MyDrive/Resell_Copilot_data")
    for fn in (VINTED_FN, KA_FN):
        dst = DATA_DIR / fn
        if dst.exists():
            continue
        src = DRIVE_DATA / fn
        if not src.exists():
            raise FileNotFoundError(
                f"{fn} not found in {DRIVE_DATA}. "
                f"Place both parquets there or copy them to {DATA_DIR}/ manually."
            )
        shutil.copy(src, dst)
        print(f"  copied {fn} from Drive")

import data_prep

vt = data_prep.apply_filters(data_prep.load_vinted(str(DATA_DIR / VINTED_FN)), "vinted")
ka = data_prep.apply_filters(data_prep.load_kleinanzeigen(str(DATA_DIR / KA_FN)), "kleinanzeigen")
vt = data_prep.filter_vinted_de_only(vt)
combined = data_prep.build_combined(vt, ka)
sampled = data_prep.stratified_sample(
    combined, n_per_platform=300,
    strata_cols=["category_name", "condition"], seed=SEED,
)
print(f"Vinted (de, filtered): {len(vt):,}")
print(f"KA      (filtered)   : {len(ka):,}")
print(f"Combined sampled     : {len(sampled):,}  {sampled['platform'].value_counts().to_dict()}")

ids_path     = SPLITS_DIR / "spike_test_ids.json"
parquet_path = SPLITS_DIR / "spike_test.parquet"

if parquet_path.exists() and ids_path.exists():
    test_df = pd.read_parquet(parquet_path)
    print(f"Reused locked test set: {parquet_path} ({len(test_df)} rows)")
else:
    train_df, test_df = data_prep.train_test_split_by_id(
        sampled, test_size=100,
        strata_cols=["category_name", "condition", "platform"], seed=SEED,
    )
    test_df.to_parquet(parquet_path, index=False)
    with open(ids_path, "w") as f:
        json.dump([int(x) for x in test_df["id"].tolist()], f)
    print(f"Wrote test set to {parquet_path} and {ids_path}")

print(f"Test by platform: {test_df['platform'].value_counts().to_dict()}")


Data files not found locally — mounting Google Drive...
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
  copied vinted_clothing_v2.parquet from Drive
  copied kleinanzeigen_clothing_v1.parquet from Drive
Vinted (de, filtered): 1,387
KA      (filtered)   : 2,302
Combined sampled     : 600  {'kleinanzeigen': 300, 'vinted': 300}
Wrote test set to data/splits/spike_test.parquet and data/splits/spike_test_ids.json
Test by platform: {'vinted': 51, 'kleinanzeigen': 49}


In [8]:
import re
import json
from typing import Optional

SCHEMA_FIELDS = ["brand", "category", "condition", "color", "size",
                 "title", "description", "price_eur"]


def parse_model_output(raw: str) -> Optional[dict]:
    """Parse a model's text output into a dict over SCHEMA_FIELDS.

    Tolerant: strips ```json / ``` fences and surrounding prose, finds the
    first matching {...} block, retries with trailing-comma cleanup if the
    JSON is slightly malformed. Missing fields become None. Returns None if
    no JSON object is parseable.
    """
    if not raw:
        return None
    text = raw.strip()
    text = re.sub(r"^```(?:json)?\s*", "", text)
    text = re.sub(r"\s*```\s*$", "", text)
    start = text.find("{")
    if start == -1:
        return None
    depth = 0
    end = -1
    for i in range(start, len(text)):
        ch = text[i]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                end = i
                break
    if end == -1:
        return None
    snippet = text[start:end + 1]
    try:
        obj = json.loads(snippet)
    except json.JSONDecodeError:
        cleaned = re.sub(r",\s*([}\]])", r"\1", snippet)
        try:
            obj = json.loads(cleaned)
        except json.JSONDecodeError:
            return None
    if not isinstance(obj, dict):
        return None
    return {k: obj.get(k) for k in SCHEMA_FIELDS}


# self-tests
for sample in [
    '```json\n{"brand": "Nike", "category": "tshirts"}\n```',
    'Hier das JSON: {"brand": "Zara", "price_eur": 20.0} — fertig.',
    '{"brand": null, "category": "jackets",}',
    'no json here at all',
]:
    print(parse_model_output(sample))


{'brand': 'Nike', 'category': 'tshirts', 'condition': None, 'color': None, 'size': None, 'title': None, 'description': None, 'price_eur': None}
{'brand': 'Zara', 'category': None, 'condition': None, 'color': None, 'size': None, 'title': None, 'description': None, 'price_eur': 20.0}
{'brand': None, 'category': 'jackets', 'condition': None, 'color': None, 'size': None, 'title': None, 'description': None, 'price_eur': None}
None


In [9]:
VINTED_CATEGORIES = ["jackets", "jeans", "tshirts", "sneakers"]
KA_CATEGORIES     = ["Damenbekleidung", "Herrenbekleidung", "Damenschuhe", "Herrenschuhe"]
CONDITION_VALUES  = ["neu mit etikett", "neu", "sehr gut", "gut"]


def get_prompt(platform: str) -> str:
    """Return the German VLM prompt template for a given platform."""
    if platform == "vinted":
        platform_name = "Vinted"
        cats = VINTED_CATEGORIES
    elif platform == "kleinanzeigen":
        platform_name = "Kleinanzeigen"
        cats = KA_CATEGORIES
    else:
        raise ValueError(f"Unknown platform: {platform}")
    cats_str = json.dumps(cats, ensure_ascii=False)
    cond_str = json.dumps(CONDITION_VALUES, ensure_ascii=False)
    return (
        f"Du bist ein Experte für {platform_name}-Inserate. "
        f"Analysiere das Foto dieses Kleidungsstücks und gib AUSSCHLIESSLICH ein "
        f"einzelnes JSON-Objekt zurück (keine Erklärungen, kein Markdown, kein Code-Fence).\n\n"
        f"Format:\n"
        f"{{\n"
        f'  "brand": <Markenname als String, oder null>,\n'
        f'  "category": <eine von {cats_str}>,\n'
        f'  "condition": <eine von {cond_str}>,\n'
        f'  "color": <Farbe auf Deutsch>,\n'
        f'  "size": <Größe als String, oder null>,\n'
        f'  "title": <Listing-Titel auf Deutsch>,\n'
        f'  "description": <Beschreibung auf Deutsch, 2-3 Sätze>,\n'
        f'  "price_eur": <Verkaufspreis in EUR als Zahl>\n'
        f"}}\n\n"
        f"Antworte nur mit dem JSON-Objekt."
    )


print("--- VINTED PROMPT ---")
print(get_prompt("vinted"))
print()
print("--- KLEINANZEIGEN PROMPT ---")
print(get_prompt("kleinanzeigen"))


--- VINTED PROMPT ---
Du bist ein Experte für Vinted-Inserate. Analysiere das Foto dieses Kleidungsstücks und gib AUSSCHLIESSLICH ein einzelnes JSON-Objekt zurück (keine Erklärungen, kein Markdown, kein Code-Fence).

Format:
{
  "brand": <Markenname als String, oder null>,
  "category": <eine von ["jackets", "jeans", "tshirts", "sneakers"]>,
  "condition": <eine von ["neu mit etikett", "neu", "sehr gut", "gut"]>,
  "color": <Farbe auf Deutsch>,
  "size": <Größe als String, oder null>,
  "title": <Listing-Titel auf Deutsch>,
  "description": <Beschreibung auf Deutsch, 2-3 Sätze>,
  "price_eur": <Verkaufspreis in EUR als Zahl>
}

Antworte nur mit dem JSON-Objekt.

--- KLEINANZEIGEN PROMPT ---
Du bist ein Experte für Kleinanzeigen-Inserate. Analysiere das Foto dieses Kleidungsstücks und gib AUSSCHLIESSLICH ein einzelnes JSON-Objekt zurück (keine Erklärungen, kein Markdown, kein Code-Fence).

Format:
{
  "brand": <Markenname als String, oder null>,
  "category": <eine von ["Damenbekleidung

In [10]:
import gc
import io
import time
from PIL import Image
from transformers import AutoProcessor, AutoModelForImageTextToText, BitsAndBytesConfig

_LOADED = {"name": None, "processor": None, "model": None}


def _free_loaded():
    if _LOADED["model"] is not None:
        del _LOADED["model"]
        del _LOADED["processor"]
    _LOADED.update(name=None, processor=None, model=None)
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.reset_peak_memory_stats()


def load_qwen(model_id: str):
    """Load (or reuse) a Qwen3-VL Instruct model in 4-bit. Frees prior model."""
    if _LOADED["name"] == model_id:
        return _LOADED["processor"], _LOADED["model"]
    _free_loaded()
    bnb_cfg = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
    )
    processor = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)
    model = AutoModelForImageTextToText.from_pretrained(
        model_id,
        quantization_config=bnb_cfg,
        device_map="auto",
        trust_remote_code=True,
    )
    model.eval()
    _LOADED.update(name=model_id, processor=processor, model=model)
    return processor, model


def pil_from_row(row) -> Image.Image:
    """Decode the HuggingFace image dict from a row into a PIL RGB image."""
    img = row["image"]
    if isinstance(img, dict) and img.get("bytes"):
        return Image.open(io.BytesIO(img["bytes"])).convert("RGB")
    if isinstance(img, (bytes, bytearray)):
        return Image.open(io.BytesIO(img)).convert("RGB")
    raise ValueError("Row has no decodable image bytes.")


def run_qwen_inference(processor, model, image: Image.Image, platform: str,
                        max_new_tokens: int = 384):
    """Run a single (image, platform) inference. Returns (raw_text, latency_seconds)."""
    prompt = get_prompt(platform)
    messages = [{
        "role": "user",
        "content": [
            {"type": "image", "image": image},
            {"type": "text", "text": prompt},
        ],
    }]
    inputs = processor.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=True,
        return_dict=True,
        return_tensors="pt",
    ).to(model.device)
    t0 = time.time()
    with torch.no_grad():
        out_ids = model.generate(**inputs, max_new_tokens=max_new_tokens, do_sample=False)
    latency = time.time() - t0
    new_tokens = out_ids[:, inputs["input_ids"].shape[1]:]
    text = processor.batch_decode(new_tokens, skip_special_tokens=True)[0]
    return text.strip(), latency


In [11]:
QWEN_MODELS = [
    "Qwen/Qwen3-VL-2B-Instruct",
    "Qwen/Qwen3-VL-4B-Instruct",
    # "Qwen/Qwen3-VL-8B-Instruct",  # disabled: OOM-risk on free Colab T4 (16 GB)
]

LOAD_RESULTS = {}  # model_id -> "ok" | failure reason

smoke_rows = test_df.sample(5, random_state=SEED).reset_index(drop=True)

for mid in QWEN_MODELS:
    print(f"\n{'='*70}\n  Smoke-testing {mid}\n{'='*70}")
    try:
        processor, model = load_qwen(mid)
    except Exception as e:
        msg = f"load_failed: {type(e).__name__}: {e}"
        print(f"  {msg}")
        LOAD_RESULTS[mid] = msg
        _free_loaded()
        continue
    try:
        for i, row in smoke_rows.iterrows():
            img = pil_from_row(row)
            raw, lat = run_qwen_inference(processor, model, img, row["platform"])
            preview = raw[:180].replace("\n", " ")
            print(f"  [{i+1}/{len(smoke_rows)}] platform={row['platform']:<14} {lat:.1f}s")
            print(f"    {preview}{'...' if len(raw) > 180 else ''}")
        LOAD_RESULTS[mid] = "ok"
    except Exception as e:
        msg = f"inference_failed: {type(e).__name__}: {e}"
        print(f"  {msg}")
        LOAD_RESULTS[mid] = msg

_free_loaded()
print("\nSmoke-test summary:")
for k, v in LOAD_RESULTS.items():
    print(f"  {k}: {v}")



  Smoke-testing Qwen/Qwen3-VL-2B-Instruct


/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:103: UserWarning: 
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(


preprocessor_config.json:   0%|          | 0.00/390 [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

video_preprocessor_config.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/4.26G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/625 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/269 [00:00<?, ?B/s]

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.


  [1/5] platform=vinted         25.6s
    {   "brand": null,   "category": "jackets",   "condition": "neu mit etikett",   "color": "beige",   "size": null,   "title": "98 - Your Wish is My Command",   "description": "Ein b...
  [2/5] platform=vinted         23.9s
    {   "brand": "Levi's",   "category": "jeans",   "condition": "neu mit etikett",   "color": "beige",   "size": "null",   "title": "Levi's Jeans - Neu mit Etikett",   "description": ...
  [3/5] platform=vinted         26.0s
    {   "brand": "Husky",   "category": "jackets",   "condition": "gut",   "color": "blau",   "size": "M",   "title": "Kurzärmeliges Jeansjacke, sehr gut erhalten",   "description": "E...
  [4/5] platform=kleinanzeigen  23.5s
    {   "brand": "Maison Michel",   "category": "Herrenbekleidung",   "condition": "gut",   "color": "blau",   "size": "null",   "title": "jeans",   "description": "jeans in gutem Zust...
  [5/5] platform=vinted         22.6s
    {   "brand": "Zara",   "category": "jeans",   "conditi

preprocessor_config.json:   0%|          | 0.00/390 [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

video_preprocessor_config.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/713 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/269 [00:00<?, ?B/s]

  [1/5] platform=vinted         29.7s
    {   "brand": null,   "category": "jackets",   "condition": "neu mit etikett",   "color": "braun",   "size": null,   "title": "Militärjacke mit 98-Logo und 'Your Wish is My Command'...
  [2/5] platform=vinted         26.2s
    {   "brand": "Levi's",   "category": "jeans",   "condition": "neu mit etikett",   "color": "Grau",   "size": null,   "title": "Levi's Jeans",   "description": "Neue Levi's Jeans mi...
  [3/5] platform=vinted         25.4s
    {   "brand": null,   "category": "jackets",   "condition": "gut",   "color": "Blau",   "size": null,   "title": "Jeansjacke",   "description": "Kurze Jeansjacke mit abgeschnittenem...
  [4/5] platform=kleinanzeigen  26.2s
    {   "brand": null,   "category": "Herrenbekleidung",   "condition": "sehr gut",   "color": "Blau",   "size": null,   "title": "Herren Jeans",   "description": "Ein Paar blaue Jeans...
  [5/5] platform=vinted         26.0s
    {   "brand": "ZARA",   "category": "jeans",   "conditi

In [12]:
def model_slug(model_id: str) -> str:
    return model_id.split("/")[-1].lower()


PERF = {}  # slug -> {"latencies": [...], "peak_vram_gb": float}


def run_full_qwen_eval(model_id: str, df: pd.DataFrame):
    slug = model_slug(model_id)
    out_path = RESULTS_DIR / f"{slug}_predictions.json"
    if out_path.exists():
        records = json.loads(out_path.read_text())
        PERF[slug] = {
            "latencies": [r["latency_s"] for r in records if "latency_s" in r],
            "peak_vram_gb": next((r.get("_peak_vram_gb_at_run") for r in records
                                  if "_peak_vram_gb_at_run" in r), None),
        }
        print(f"  cached: {out_path}  ({len(records)} rows)")
        return out_path
    if LOAD_RESULTS.get(model_id) != "ok":
        print(f"  skipped ({LOAD_RESULTS.get(model_id, 'not smoke-tested')})")
        return None

    processor, model = load_qwen(model_id)
    if torch.cuda.is_available():
        torch.cuda.reset_peak_memory_stats()

    records = []
    for i, row in df.iterrows():
        try:
            img = pil_from_row(row)
            raw, lat = run_qwen_inference(processor, model, img, row["platform"])
            parsed = parse_model_output(raw)
        except Exception as e:
            raw, lat, parsed = f"ERROR: {type(e).__name__}: {e}", 0.0, None
        records.append({
            "id": int(row["id"]),
            "platform": row["platform"],
            "raw": raw,
            "parsed": parsed,
            "ground_truth": {
                "brand":       row.get("brand"),
                "category":    row.get("category_name"),
                "condition":   row.get("condition"),
                "color":       row.get("color"),
                "size":        row.get("size"),
                "title":       row.get("title"),
                "description": row.get("description"),
                "price_eur":   float(row["price"]) if pd.notna(row.get("price")) else None,
            },
            "latency_s": lat,
        })
        if (i + 1) % 20 == 0:
            print(f"    {i+1}/{len(df)}")

    peak_vram_gb = (torch.cuda.max_memory_allocated() / 1e9) if torch.cuda.is_available() else 0.0
    if records:
        records[0]["_peak_vram_gb_at_run"] = peak_vram_gb
    out_path.write_text(json.dumps(records, indent=2, default=str, ensure_ascii=False))
    PERF[slug] = {"latencies": [r["latency_s"] for r in records], "peak_vram_gb": peak_vram_gb}
    print(f"  wrote {out_path}  (peak VRAM {peak_vram_gb:.2f} GB)")
    return out_path


for mid in QWEN_MODELS:
    print(f"\nFull eval: {mid}")
    run_full_qwen_eval(mid, test_df)

_free_loaded()



Full eval: Qwen/Qwen3-VL-2B-Instruct


Loading weights:   0%|          | 0/625 [00:00<?, ?it/s]

    20/100
    40/100
    60/100
    80/100
    100/100
  wrote results/spike/qwen3-vl-2b-instruct_predictions.json  (peak VRAM 5.59 GB)

Full eval: Qwen/Qwen3-VL-4B-Instruct


Loading weights:   0%|          | 0/713 [00:00<?, ?it/s]

    20/100
    40/100
    60/100
    80/100
    100/100
  wrote results/spike/qwen3-vl-4b-instruct_predictions.json  (peak VRAM 7.04 GB)


In [13]:
import base64
import getpass
from openai import OpenAI

GPT_MODEL    = "gpt-4o-mini"
GPT_HARD_CAP = 100   # max API calls; safety net
GPT_OUT      = RESULTS_DIR / "gpt4omini_predictions.json"

if GPT_OUT.exists():
    print(f"cached: {GPT_OUT}")
    cached = json.loads(GPT_OUT.read_text())
    PERF["gpt-4o-mini"] = {"latencies": [r["latency_s"] for r in cached], "peak_vram_gb": 0.0}
else:
    api_key = os.environ.get("OPENAI_API_KEY") or getpass.getpass("OPENAI_API_KEY: ")
    client = OpenAI(api_key=api_key)

    def img_to_data_url(img):
        buf = io.BytesIO()
        img.save(buf, format="JPEG", quality=85)
        return "data:image/jpeg;base64," + base64.b64encode(buf.getvalue()).decode()

    records = []
    n_calls = 0
    for i, row in test_df.iterrows():
        if n_calls >= GPT_HARD_CAP:
            print(f"  hit hard cap of {GPT_HARD_CAP}, stopping")
            break
        try:
            img = pil_from_row(row)
            t0 = time.time()
            resp = client.chat.completions.create(
                model=GPT_MODEL,
                messages=[{
                    "role": "user",
                    "content": [
                        {"type": "image_url",
                         "image_url": {"url": img_to_data_url(img)}},
                        {"type": "text", "text": get_prompt(row["platform"])},
                    ],
                }],
                max_tokens=400,
                temperature=0.0,
            )
            lat = time.time() - t0
            raw = resp.choices[0].message.content
            n_calls += 1
            parsed = parse_model_output(raw)
        except Exception as e:
            raw, lat, parsed = f"ERROR: {type(e).__name__}: {e}", 0.0, None

        records.append({
            "id": int(row["id"]),
            "platform": row["platform"],
            "raw": raw,
            "parsed": parsed,
            "ground_truth": {
                "brand":       row.get("brand"),
                "category":    row.get("category_name"),
                "condition":   row.get("condition"),
                "color":       row.get("color"),
                "size":        row.get("size"),
                "title":       row.get("title"),
                "description": row.get("description"),
                "price_eur":   float(row["price"]) if pd.notna(row.get("price")) else None,
            },
            "latency_s": lat,
        })
        if (i + 1) % 20 == 0:
            print(f"  {i+1}/{len(test_df)}  (api_calls={n_calls})")

    GPT_OUT.write_text(json.dumps(records, indent=2, default=str, ensure_ascii=False))
    PERF["gpt-4o-mini"] = {"latencies": [r["latency_s"] for r in records], "peak_vram_gb": 0.0}
    print(f"  wrote {GPT_OUT}  ({n_calls} API calls)")


  20/100  (api_calls=16)
  40/100  (api_calls=21)
  60/100  (api_calls=23)
  80/100  (api_calls=25)
  100/100  (api_calls=30)
  wrote results/spike/gpt4omini_predictions.json  (30 API calls)


## How to read the metrics table

| column          | meaning                                                                  |
|-----------------|--------------------------------------------------------------------------|
| `n`             | number of test rows scored                                               |
| `parse_rate`    | fraction of rows where the model emitted parseable JSON                  |
| `brand_acc`     | exact-match brand accuracy (case-normalized) on rows where GT exists     |
| `category_acc`  | top-1 category match against the row's own platform vocabulary           |
| `condition_acc` | top-1 condition match on the 4 normalized buckets                        |
| `color_acc`     | top-1 color match (case-normalized German label)                         |
| `price_mape`    | mean absolute % error on rows where price was parsed                     |
| `price_n`       | rows contributing to MAPE (≈ `parse_rate × n`)                           |

Brand and condition are the hardest fields zero-shot — image alone rarely reveals them. Category is the easiest. Price is universally bad zero-shot; the Day 2 quantile head fixes this.

In [14]:
def _norm(v):
    return None if v is None else str(v).lower().strip()


def compute_metrics(records: list) -> dict:
    n = len(records)
    if n == 0:
        return {"n": 0}

    parsed_ok = sum(1 for r in records if r["parsed"] is not None)
    correct = {"brand": 0, "category": 0, "condition": 0, "color": 0}
    valid   = {"brand": 0, "category": 0, "condition": 0, "color": 0}
    abs_pct_errs = []

    for r in records:
        p, gt = r["parsed"], r["ground_truth"]
        if p is None:
            continue
        for f in ("brand", "category", "condition", "color"):
            true = gt.get(f)
            if true is None:
                continue
            valid[f] += 1
            if _norm(p.get(f)) == _norm(true):
                correct[f] += 1
        try:
            pred_price = float(p.get("price_eur"))
            true_price = float(gt.get("price_eur"))
            if true_price > 0:
                abs_pct_errs.append(abs(pred_price - true_price) / true_price)
        except (TypeError, ValueError):
            pass

    return {
        "n":            n,
        "parse_rate":   parsed_ok / n,
        "brand_acc":    (correct["brand"]     / valid["brand"])     if valid["brand"]     else None,
        "category_acc": (correct["category"]  / valid["category"])  if valid["category"]  else None,
        "condition_acc":(correct["condition"] / valid["condition"]) if valid["condition"] else None,
        "color_acc":    (correct["color"]     / valid["color"])     if valid["color"]     else None,
        "price_mape":   float(np.mean(abs_pct_errs)) if abs_pct_errs else None,
        "price_n":      len(abs_pct_errs),
    }


PRED_FILES = []
for mid in QWEN_MODELS:
    p = RESULTS_DIR / f"{model_slug(mid)}_predictions.json"
    if p.exists():
        PRED_FILES.append((model_slug(mid), p))
if (RESULTS_DIR / "gpt4omini_predictions.json").exists():
    PRED_FILES.append(("gpt-4o-mini", RESULTS_DIR / "gpt4omini_predictions.json"))

rows = []
for name, path in PRED_FILES:
    rows.append({"model": name, **compute_metrics(json.loads(path.read_text()))})

metrics_df = pd.DataFrame(rows)
print(metrics_df.to_markdown(index=False, floatfmt=".3f"))


| model                |   n |   parse_rate |   brand_acc |   category_acc |   condition_acc |   color_acc |   price_mape |   price_n |
|:---------------------|----:|-------------:|------------:|---------------:|----------------:|------------:|-------------:|----------:|
| qwen3-vl-2b-instruct | 100 |        1.000 |       0.270 |          0.830 |           0.280 |       0.600 |        1.483 |       100 |
| qwen3-vl-4b-instruct | 100 |        1.000 |       0.230 |          0.930 |           0.640 |       0.630 |        1.080 |       100 |
| gpt-4o-mini          | 100 |        0.300 |       0.333 |          0.867 |           0.300 |       0.600 |        1.093 |        30 |


In [15]:
perf_rows = []
for slug, perf in PERF.items():
    lats = perf.get("latencies", [])
    perf_rows.append({
        "model":            slug,
        "n_calls":          len(lats),
        "median_latency_s": float(np.median(lats))         if lats else None,
        "p95_latency_s":    float(np.percentile(lats, 95)) if lats else None,
        "peak_vram_gb":     perf.get("peak_vram_gb"),
    })
perf_df = pd.DataFrame(perf_rows)
print(perf_df.to_markdown(index=False, floatfmt=".2f"))


| model                |   n_calls |   median_latency_s |   p95_latency_s |   peak_vram_gb |
|:---------------------|----------:|-------------------:|----------------:|---------------:|
| qwen3-vl-2b-instruct |       100 |              22.79 |           24.99 |           5.59 |
| qwen3-vl-4b-instruct |       100 |              26.43 |           28.47 |           7.04 |
| gpt-4o-mini          |       100 |               0.00 |            3.53 |           0.00 |


## Verdict

**Locked model for Day 2: `Qwen/Qwen3-VL-4B-Instruct`.**

### Why

Beats GPT-4o-mini on 4 of 6 metrics on the same 100-row test set:

| metric          | Qwen 4B  | GPT-4o-mini | margin     |
|-----------------|----------|-------------|------------|
| parse_rate      | 1.000    | 0.300       | **+0.70**  |
| category_acc    | 0.930    | 0.867       | **+0.06**  |
| condition_acc   | 0.640    | 0.300       | **+0.34**  |
| price_mape      | 1.080    | 1.093       | **+0.01**  |
| brand_acc       | 0.230    | 0.333       | −0.10      |
| color_acc       | 0.630    | 0.600       | +0.03      |

It also beats Qwen 2B on every metric, most dramatically on condition (0.640 vs 0.280). Peak VRAM 7.04 GB at 4-bit fits comfortably on a free T4 — Day 2 QLoRA on a 4090 has plenty of headroom.

Qwen 4B clears the bar (beats GPT-4o-mini on ≥1 of {brand, category, price MAPE}) on **category** and marginally on **price MAPE**. **Idea works → commit, scale up Day 2.**

### Notable failure modes seen in raw outputs

- **Brand accuracy is weak across all models (0.23 – 0.33).** Photos rarely show readable brand tags; models can't infer brand from style alone. Aligns with brief §7's documented limitation ("brand labels are seller-claimed"). The Day 2 fine-tune may lift this somewhat by learning brand-style associations from training data, but the ceiling is structural.
- **Price MAPE > 1.0 across all models.** Zero-shot pricing is essentially guessing. The Day 2 architecture (log-transform target + 5-quantile pinball loss + categorical / brand / platform features) is the right fix; the brief's design holds.
- **GPT-4o-mini's 30% parse rate.** With our German strict-JSON prompt, GPT-4o-mini emits prose or wraps JSON in fences ~70% of the time. The 30 successfully parsed rows likely skew toward easier examples, so its accuracy numbers are over-optimistic. Worth iterating on the prompt if we want a stronger baseline for the deck — for the *model-selection* question, the parse-rate gap alone is decisive.
- **Qwen 2B condition_acc = 0.280** (vs 4B's 0.640). The smaller model is too weak for the harder semantic fields — confirms 4B is the right tier, not 2B.

### Latency / VRAM (cell 13 table)

| model        | median  | p95     | peak VRAM |
|--------------|---------|---------|-----------|
| Qwen 2B      | 22.8 s  | 25.0 s  | 5.6 GB    |
| Qwen 4B      | 26.4 s  | 28.5 s  | 7.0 GB    |
| GPT-4o-mini  | n/a\*   | 3.5 s   | n/a       |

\*GPT median is 0 because failed calls record latency 0; the 3.5 s p95 reflects the 30 successful API calls.

T4 inference at ~26 s per call is too slow for a live demo; we will batch or move inference to a 4090 on Day 5. Not a blocker for the Day 2 fine-tune.

### Why 8B was not tested

`Qwen/Qwen3-VL-8B-Instruct` is commented out in cell 9 — 4-bit weights are ~5 GB but activations + KV cache push past 16 GB on T4 for our 384-token generation length. If Day 2 reveals 4B fine-tuned still doesn't beat zero-shot baselines by enough margin, escalate to 8B on a RunPod A100 (per brief §10.3).

## Files left on disk

| path                                                  | what                                          |
|-------------------------------------------------------|-----------------------------------------------|
| `data/splits/spike_test.parquet`                      | locked 100-row test set (frozen by SEED)      |
| `data/splits/spike_test_ids.json`                     | list of test `id`s, for split reproducibility |
| `results/spike/qwen3-vl-2b-instruct_predictions.json` | raw + parsed outputs + GT + per-row latency  |
| `results/spike/qwen3-vl-4b-instruct_predictions.json` | same shape as above                           |
| `results/spike/gpt4omini_predictions.json`            | same shape, OpenAI baseline                   |

## What this notebook does NOT test

- **Fine-tuned performance.** Day 2 — the QLoRA fine-tune is the headline metric for the pitch.
- **Visible-flaw head, price head, sell-likelihood head.** Day 2–3, see brief §3.
- **Prompt sensitivity.** One prompt per platform; no ablation.
- **Multi-image listings.** One hero shot per item.
- **French / Italian / English Vinted rows.** Filtered to German for the spike (revisit post-spike).
- **Post-edit verify flow / publish flow.** Backend work, Day 3+.

These are deliberately deferred. The spike's job is "does the idea work?" — answer: yes.

## Next step

Day 2: full data pipeline + QLoRA fine-tune of Qwen3-VL-4B-Instruct on RunPod (4090 community cloud, ~$0.35/hr, ~2–3 hrs per the brief estimate). Re-run this notebook's eval against the fine-tuned adapter and report the fine-tune-vs-zero-shot delta — that is what goes in the pitch deck.